# Generated by Django 5.2.7 on 2026-08-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'permissions': [('assign_lead', 'Can assign lead'), ('progress_lead', 'Can progress lead'), ('mark_lead_lost', 'Can mark lead as lost'), ('reengage_lead', 'Can re-engage lead'), ('convert_lead', 'Can convert lead to customer')]},
        ),
        migrations.AlterModelOptions(
            name='leadsource',
            options={'ordering': ['name'], 'permissions': [('manage_lead_source', 'Can manage lead source')]},
        ),
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['name'], 'permissions': [('manage_pipeline', 'Can manage pipeline')]},
        ),
        migrations.AlterModelOptions(
            name='pipelinestage',
            options={'ordering': ['pipeline', 'display_order'], 'permissions': [('manage_pipeline_stage', 'Can manage pipeline stage')]},
        ),
    ]
