# Generated by Django 5.2.7 on 2026-08-13 07:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_alter_lead_options_alter_leadsource_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='quotation_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='requires_quotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('DEMO', 'Demo'), ('FOLLOW_UP', 'Follow Up'), ('QUOTATION_CREATED', 'Quotation Created'), ('QUOTATION_UPDATED', 'Quotation Updated'), ('QUOTATION_SUBMITTED', 'Quotation Submitted'), ('QUOTATION_APPROVED', 'Quotation Approved'), ('QUOTATION_APPROVAL_REJECTED', 'Quotation Approval Rejected'), ('QUOTATION_SENT', 'Quotation Sent'), ('QUOTATION_REVISION_REQUESTED', 'Quotation Revision Requested'), ('QUOTATION_VERSION_CREATED', 'Quotation Version Created'), ('QUOTATION_ACCEPTED', 'Quotation Accepted'), ('QUOTATION_REJECTED', 'Quotation Rejected')], max_length=30),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('REVISED', 'Revised')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customer_management.customer')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customer_management.lead')),
            ],
            options={
                'db_table': 'quotation',
                'ordering': ['-created_at'],
                'permissions': [('submit_quotation', 'Can submit quotation for approval'), ('approve_quotation', 'Can approve quotation'), ('send_quotation', 'Can send quotation'), ('accept_quotation', 'Can accept quotation'), ('reject_quotation', 'Can reject quotation'), ('request_quotation_revision', 'Can request quotation revision')],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='customer_management.quotation'),
        ),
        migrations.CreateModel(
            name='QuotationIntegrationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('quotation_version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONSUMED', 'Consumed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_integration_events', to='customer_management.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_integration_events', to='customer_management.lead')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to='customer_management.quotation')),
            ],
            options={
                'db_table': 'quotation_integration_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested'), ('REVISED', 'Revised')], default='DRAFT', max_length=30)),
                ('approval_required', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('terms', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_quotation_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quotation_versions', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_versions', to='customer_management.pipelinestage')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_versions', to='customer_management.pipeline')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='customer_management.quotation')),
            ],
            options={
                'db_table': 'quotation_version',
                'ordering': ['quotation', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='customer_management.quotationversion')),
            ],
            options={
                'db_table': 'quotation_line_item',
                'ordering': ['version', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_quotation_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_quotation_approvals', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='customer_management.quotationversion')),
            ],
            options={
                'db_table': 'quotation_approval',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer_management.quotationversion'),
        ),
        migrations.AddConstraint(
            model_name='quotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_number'), name='unique_quotation_version'),
        ),
    ]
