# Generated by Django 5.2.7 on 2026-08-14 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer_management",
            "0003_pipelinestage_quotation_approval_required_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_to", "status"], name="lead_assigned_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["pipeline", "current_stage"], name="lead_pipeline_stage_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["created_at"], name="lead_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["lead", "status"], name="quotation_lead_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["created_at"], name="quotation_created_at_idx"),
        ),
    ]
