# Generated by Django 5.2.7 on 2026-08-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_management", "0006_alter_quotation_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
