# Generated by Django 5.2.7 on 2026-08-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_management",
            "0007_remove_auditlog_user_delete_activity_delete_auditlog",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("email",), name="uq_customer_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("phone",), name="uq_customer_phone"
            ),
        ),
    ]
