# Generated by Django 5.2.7 on 2026-08-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_management",
            "0010_lead_due_amount_lead_financial_status_lead_metadata_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipeline",
            name="pipeline_type",
        ),
    ]
