# Generated by Django 5.2.7 on 2026-08-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Followup",
            fields=[
                ("followup_id", models.AutoField(primary_key=True, serialize=False)),
                ("followup_date", models.DateTimeField()),
                ("decription", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpStatus",
            fields=[
                (
                    "followup_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("status_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpTypes",
            fields=[
                (
                    "followup_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
