# Generated by Django 5.2.7 on 2026-08-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FollowUp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FollowUpNote",
        ),
    ]
