# Generated by Django 5.2.7 on 2026-08-26 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("FollowUp", "0001_initial"),
        ("Task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_followups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="task_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followups",
                to="Task.task",
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="followup_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="followups",
                to="FollowUp.followupstatus",
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="followup_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="followups",
                to="FollowUp.followuptypes",
            ),
        ),
    ]
