# Generated by Django 5.2.7 on 2026-08-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FollowUp", "0002_notification_edited_by_notification_is_customized_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"permissions": [("send_notification", "Can send notification")]},
        ),
    ]
