# Generated by Django 5.2.7 on 2026-08-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_customer_task_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
