# Generated by Django 5.2.7 on 2026-08-18 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0006_alter_meeting_meeting_status_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "Task_reminder" ADD COLUMN IF NOT EXISTS "reminder_for_id" uuid REFERENCES accounts_customuser(user_id) DEFERRABLE INITIALLY DEFERRED;',
            reverse_sql='ALTER TABLE "Task_reminder" DROP COLUMN IF EXISTS "reminder_for_id";',
        ),
        migrations.AlterField(
            model_name="reminder",
            name="reminder_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
