# Generated by Django 5.2.7 on 2026-08-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0007_merge_20260814_1547"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="is_sent",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="reminder_for",
        ),
    ]
