# Generated by Django 5.2.7 on 2026-08-19 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0007_alter_reminder_reminder_for"),
        ("customer_management", "0006_alter_quotation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="customer_management.lead",
            ),
        ),
    ]
