# Generated by Django 5.2.7 on 2026-08-19 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0008_remove_reminder_is_sent_remove_reminder_reminder_for"),
        ("customer_management", "0006_alter_quotation_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reminder",
            name="reminder_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="customer_management.lead",
            ),
        ),
    ]
