# Generated by Django 5.2.7 on 2026-08-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0008_remove_reminder_is_sent_remove_reminder_reminder_for"),
        ("Task", "0009_reminder_is_sent_reminder_reminder_for_and_more"),
    ]

    operations = []
