# Generated by Django 5.2.7 on 2026-08-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0010_merge_20260820_1453"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
    ]
