# Generated by Django 5.2.7 on 2026-08-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0012_add_meeting_participant_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reminder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
