# Generated by Django 5.2.7 on 2026-08-21 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0012_meeting_approval_status_meeting_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_meetings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
