# Generated by Django 5.2.7 on 2026-08-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0013_add_is_active_soft_delete_fields"),
        ("Task", "0013_alter_meeting_manager"),
    ]

    operations = []
