# Generated by Django 5.2.7 on 2026-08-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0014_task_form_submission"),
        ("Task", "0015_meeting_extra_fields"),
    ]

    operations = []
