# Generated by Django 5.2.7 on 2026-08-20 12:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_management", "0008_add_customer_unique_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationlineitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
