# Generated by Django 5.2.7 on 2026-08-24 05:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_management", "0009_alter_quotationlineitem_unit_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="due_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="financial_status",
            field=models.CharField(
                choices=[
                    ("NO_DUES", "No Outstanding Dues"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("PAYMENT_OVERDUE", "Payment Overdue"),
                ],
                default="NO_DUES",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lead",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="total_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="entity_label",
            field=models.CharField(
                default="Deal",
                help_text="Custom label for engagement items in this pipeline (e.g. 'Project', 'Product Order', 'Ticket').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="pipeline_type",
            field=models.CharField(
                choices=[
                    ("DEAL", "B2B Deal / Sales Opportunity"),
                    ("PROJECT", "Service / Implementation Project"),
                    ("PRODUCT_ORDER", "Product Purchase / E-Commerce Order"),
                    ("SERVICE_TICKET", "Service Request / Warranty Support"),
                    ("GENERAL", "General Inquiry"),
                ],
                default="DEAL",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer",
                to="customer_management.lead",
            ),
        ),
        migrations.CreateModel(
            name="CustomerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(db_index=True, max_length=255)),
                (
                    "gst_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, unique=True
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "primary_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customer_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customer_account",
                "ordering": ["company_name"],
                "permissions": [
                    ("manage_customer_account", "Can manage customer account")
                ],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="customer_management.customeraccount",
            ),
        ),
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="customer_management.customeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "customer_contact",
                "ordering": ["name"],
                "permissions": [
                    ("manage_customer_contact", "Can manage customer contact")
                ],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="customer_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="customer_management.customercontact",
            ),
        ),
    ]
