# Generated by Django 5.2.7 on 2026-09-02 05:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_management", "0011_remove_pipeline_pipeline_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationlineitem",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="quotationlineitem",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("18.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="quotationlineitem",
            name="hsn_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="quotationversion",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("FLAT", "Flat"), ("PERCENT", "Percent")],
                default="FLAT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quotationversion",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="quotationversion",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="quotationversion",
            name="subtotal_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=18
            ),
        ),
    ]
