# Generated by Django 5.2.7 on 2026-09-02 09:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_management", "0012_add_discount_gst_hsn"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("assign_lead", "Can assign lead"),
                    ("progress_lead", "Can progress lead"),
                    ("mark_lead_lost", "Can mark lead as lost"),
                    ("reengage_lead", "Can re-engage lead"),
                    ("convert_lead", "Can convert lead to customer"),
                    ("record_payment", "Can record payment for lead/customer"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("UPI", "UPI"),
                            ("CHEQUE", "Cheque"),
                            ("ONLINE", "Online Gateway"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="customer_management.customer",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="customer_management.lead",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["lead"], name="payment_lead_idx"),
                    models.Index(fields=["customer"], name="payment_customer_idx"),
                ],
            },
        ),
    ]
