# Generated by Django 5.2.7 on 2026-08-17 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FollowUp", "0003_alter_notification_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followup_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
