# Generated by Django 5.2.7 on 2026-08-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FollowUp", "0004_alter_notification_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationtemplate",
            name="notification_type_id",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="NotificationTemplate",
        ),
        migrations.DeleteModel(
            name="NotificationType",
        ),
    ]
