# Generated by Django 5.2.7 on 2026-08-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FollowUp", "0005_remove_notificationtemplate_notification_type_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="activity_action_id",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="activity_type_id",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="ActivityAction",
        ),
        migrations.DeleteModel(
            name="ActivityType",
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
