# Generated by Django 5.2.7 on 2026-08-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FollowUp", "0006_remove_activitylog_activity_action_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
