# Generated by Django 5.2.7 on 2026-08-24 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CallForms", "0003_adhocfieldproposal_indexedsubmissionvalue"),
        ("Task", "0013_add_is_active_soft_delete_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="form_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="CallForms.formsubmission",
            ),
        ),
    ]
