# Generated by Django 5.2.7 on 2026-08-26 09:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdhocFieldProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text Area"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("select", "Select"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("help_text", models.TextField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "adhoc_field_proposal",
                "ordering": ["-created_at"],
                "permissions": [
                    ("add_adhoc_field", "Can propose ad-hoc field"),
                    ("manage_adhoc_field", "Can manage/review ad-hoc field proposal"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CallAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("NO_ANSWER", "No Answer"),
                            ("BUSY", "Busy"),
                            ("CONNECTED", "Connected"),
                            ("CALLBACK", "Callback Scheduled"),
                            ("COMPLETED", "Form Completed"),
                            (
                                "LOST_SUGGESTED",
                                "Threshold Reached - Mark Lost Suggested",
                            ),
                        ],
                        default="NO_ANSWER",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_form_submitted", models.BooleanField(default=False)),
                ("suggest_mark_lost", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "call_attempt",
                "ordering": ["lead", "-attempt_number", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "call_template",
                "ordering": ["name"],
                "permissions": [("manage_call_template", "Can manage call template")],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "form_submission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndexedSubmissionValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_key", models.CharField(db_index=True, max_length=100)),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "value_number",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("value_date", models.DateField(blank=True, db_index=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "indexed_submission_value",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStageActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Call"),
                            ("MEETING", "Meeting"),
                            ("EMAIL", "Email"),
                            ("FOLLOWUP", "Follow-up"),
                        ],
                        default="CALL",
                        max_length=50,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pipeline_stage_activity",
                "ordering": ["stage", "display_order", "name"],
                "permissions": [("manage_stage_activity", "Can manage stage activity")],
            },
        ),
        migrations.CreateModel(
            name="TaskTriggerRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "trigger_condition",
                    models.CharField(
                        choices=[
                            ("ALWAYS", "Always Trigger on Submission"),
                            ("FOLLOW_UP_REQUIRED", "When Follow-Up is Required"),
                            ("OUTCOME_MATCH", "When Call Attempt Outcome Matches"),
                            ("FIELD_VALUE_MATCH", "When Specific Field Matches Value"),
                        ],
                        default="ALWAYS",
                        max_length=50,
                    ),
                ),
                (
                    "condition_field_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("condition_value", models.JSONField(blank=True, default=dict)),
                (
                    "task_title_template",
                    models.CharField(
                        default="Follow-up with {lead_name}",
                        help_text="Title template supporting {lead_name}, {stage_name}, {template_name}",
                        max_length=200,
                    ),
                ),
                ("due_days_offset", models.PositiveIntegerField(default=1)),
                (
                    "assignee_rule",
                    models.CharField(
                        choices=[
                            ("CONDUCTING_AGENT", "Conducting Agent"),
                            ("LEAD_OWNER", "Lead Assigned Owner"),
                            ("SPECIFIC_USER", "Specific User"),
                        ],
                        default="CONDUCTING_AGENT",
                        max_length=50,
                    ),
                ),
                ("create_reminder", models.BooleanField(default=True)),
                ("reminder_minutes_before", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "task_trigger_rule",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text Area"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("select", "Select"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("help_text", models.TextField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, default=list)),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "template_field",
                "ordering": ["template_version", "display_order", "field_key"],
                "permissions": [("manage_template_field", "Can manage template field")],
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("version_label", models.CharField(blank=True, max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "template_version",
                "ordering": ["template", "-version_number"],
                "permissions": [
                    ("manage_template_version", "Can manage template version")
                ],
            },
        ),
    ]
