# Generated by Django 5.2.7 on 2026-08-24 04:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer_management", "0009_alter_quotationlineitem_unit_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_call_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "call_template",
                "ordering": ["name"],
                "permissions": [("manage_call_template", "Can manage call template")],
            },
        ),
        migrations.CreateModel(
            name="PipelineStageActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Call"),
                            ("MEETING", "Meeting"),
                            ("EMAIL", "Email"),
                            ("FOLLOWUP", "Follow-up"),
                        ],
                        default="CALL",
                        max_length=50,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_activities",
                        to="CallForms.calltemplate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_stage_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="customer_management.pipelinestage",
                    ),
                ),
            ],
            options={
                "db_table": "pipeline_stage_activity",
                "ordering": ["stage", "display_order", "name"],
                "permissions": [("manage_stage_activity", "Can manage stage activity")],
            },
        ),
        migrations.CreateModel(
            name="CallAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("NO_ANSWER", "No Answer"),
                            ("BUSY", "Busy"),
                            ("CONNECTED", "Connected"),
                            ("CALLBACK", "Callback Scheduled"),
                            ("COMPLETED", "Form Completed"),
                            (
                                "LOST_SUGGESTED",
                                "Threshold Reached - Mark Lost Suggested",
                            ),
                        ],
                        default="NO_ANSWER",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_form_submitted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conducted_call_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_attempts",
                        to="customer_management.lead",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_attempts",
                        to="customer_management.pipelinestage",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_attempts",
                        to="CallForms.pipelinestageactivity",
                    ),
                ),
            ],
            options={
                "db_table": "call_attempt",
                "ordering": ["lead", "-attempt_number", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("version_label", models.CharField(blank=True, max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="CallForms.calltemplate",
                    ),
                ),
            ],
            options={
                "db_table": "template_version",
                "ordering": ["template", "-version_number"],
                "permissions": [
                    ("manage_template_version", "Can manage template version")
                ],
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Text Area"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("select", "Select"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("help_text", models.TextField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, default=list)),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="CallForms.templateversion",
                    ),
                ),
            ],
            options={
                "db_table": "template_field",
                "ordering": ["template_version", "display_order", "field_key"],
                "permissions": [("manage_template_field", "Can manage template field")],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "call_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_submissions",
                        to="CallForms.callattempt",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_submissions",
                        to="customer_management.lead",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="CallForms.templateversion",
                    ),
                ),
            ],
            options={
                "db_table": "form_submission",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="callattempt",
            name="template_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_attempts",
                to="CallForms.templateversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinestageactivity",
            constraint=models.UniqueConstraint(
                fields=("stage", "name"), name="unique_stage_activity_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="templateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version_number"),
                name="unique_template_version_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatefield",
            constraint=models.UniqueConstraint(
                fields=("template_version", "field_key"),
                name="unique_template_field_key",
            ),
        ),
    ]
