# Generated by Django 5.2.7 on 2026-08-24 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CallForms", "0001_initial"),
        ("Task", "0013_add_is_active_soft_delete_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTriggerRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "trigger_condition",
                    models.CharField(
                        choices=[
                            ("ALWAYS", "Always Trigger on Submission"),
                            ("FOLLOW_UP_REQUIRED", "When Follow-Up is Required"),
                            ("OUTCOME_MATCH", "When Call Attempt Outcome Matches"),
                            ("FIELD_VALUE_MATCH", "When Specific Field Matches Value"),
                        ],
                        default="ALWAYS",
                        max_length=50,
                    ),
                ),
                (
                    "condition_field_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("condition_value", models.JSONField(blank=True, default=dict)),
                (
                    "task_title_template",
                    models.CharField(
                        default="Follow-up with {lead_name}",
                        help_text="Title template supporting {lead_name}, {stage_name}, {template_name}",
                        max_length=200,
                    ),
                ),
                ("due_days_offset", models.PositiveIntegerField(default=1)),
                (
                    "assignee_rule",
                    models.CharField(
                        choices=[
                            ("CONDUCTING_AGENT", "Conducting Agent"),
                            ("LEAD_OWNER", "Lead Assigned Owner"),
                            ("SPECIFIC_USER", "Specific User"),
                        ],
                        default="CONDUCTING_AGENT",
                        max_length=50,
                    ),
                ),
                ("create_reminder", models.BooleanField(default=True)),
                ("reminder_minutes_before", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "specific_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callform_assigned_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callform_trigger_rules",
                        to="Task.taskcategory",
                    ),
                ),
                (
                    "task_priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callform_trigger_rules",
                        to="Task.taskpriority",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trigger_rules",
                        to="CallForms.templateversion",
                    ),
                ),
            ],
            options={
                "db_table": "task_trigger_rule",
                "ordering": ["name"],
            },
        ),
    ]
