# Generated by Django 5.2.7 on 2026-08-24 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CallForms", "0003_adhocfieldproposal_indexedsubmissionvalue"),
        (
            "customer_management",
            "0010_lead_due_amount_lead_financial_status_lead_metadata_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="callattempt",
            name="suggest_mark_lost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_submissions",
                to="customer_management.quotation",
            ),
        ),
    ]
