# Generated by Django 5.2.7 on 2026-09-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CallForms", "0004_callattempt_suggest_mark_lost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinestageactivity",
            name="allowed_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pipelinestageactivity",
            name="auto_create_followup",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pipelinestageactivity",
            name="followup_offset_days",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="adhocfieldproposal",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Text Area"),
                    ("number", "Number"),
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("datetime", "Date & Time"),
                    ("select", "Select"),
                    ("radio", "Radio"),
                    ("checkbox", "Checkbox"),
                    ("file", "File Upload"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Text Area"),
                    ("number", "Number"),
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("datetime", "Date & Time"),
                    ("select", "Select"),
                    ("radio", "Radio"),
                    ("checkbox", "Checkbox"),
                    ("file", "File Upload"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
