# Generated by Django 5.2.7 on 2026-09-01 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CallForms", "0005_pipelinestageactivity_allowed_roles_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callattempt",
            options={
                "ordering": ["lead", "-attempt_number", "-created_at"],
                "permissions": [
                    ("can_create_followup", "Can create followup from call")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="pipelinestageactivity",
            options={
                "ordering": ["stage", "display_order", "name"],
                "permissions": [
                    ("manage_stage_activity", "Can manage stage activity"),
                    ("manage_pipeline_stage_form", "Can manage pipeline stage form"),
                ],
            },
        ),
        migrations.AddField(
            model_name="pipelinestageactivity",
            name="editable_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pipelinestageactivity",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("CALL", "Call"),
                    ("PROPOSAL", "Proposal"),
                    ("OFFER", "Offer"),
                    ("CONTRACT", "Contract"),
                    ("CUSTOM", "Custom"),
                ],
                default="CALL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="callattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("NO_ANSWER", "No Answer"),
                    ("BUSY", "Busy"),
                    ("CONNECTED", "Connected"),
                    ("CALLBACK", "Callback Scheduled"),
                    ("WRONG_NUMBER", "Wrong Number"),
                    ("DO_NOT_CALL", "Do Not Call"),
                    ("COMPLETED", "Form Completed"),
                    ("LOST_SUGGESTED", "Threshold Reached - Mark Lost Suggested"),
                ],
                default="NO_ANSWER",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="FormFieldMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_key", models.CharField(max_length=100)),
                (
                    "target_model",
                    models.CharField(
                        choices=[
                            ("Lead", "Lead"),
                            ("Customer", "Customer"),
                            ("CustomerAccount", "CustomerAccount"),
                        ],
                        default="Lead",
                        max_length=30,
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        help_text="e.g. gst_number, company_name, metadata.annual_revenue",
                        max_length=100,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="CallForms.calltemplate",
                    ),
                ),
            ],
            options={
                "db_table": "form_field_mapping",
                "ordering": ["template", "field_key"],
                "unique_together": {("template", "field_key")},
            },
        ),
    ]
