# Generated by Django 5.2.7 on 2026-08-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("meeting_id", models.AutoField(primary_key=True, serialize=False)),
                ("meeting_title", models.CharField(max_length=100)),
                ("meeting_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("meeting_link", models.URLField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Manager Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extra_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom dynamic fields added by employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                ("participant_id", models.AutoField(primary_key=True, serialize=False)),
                ("participant_role", models.CharField(max_length=100)),
                ("is_required", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingStatus",
            fields=[
                (
                    "meeting_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("status_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingType",
            fields=[
                (
                    "meeting_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("reminder_id", models.AutoField(primary_key=True, serialize=False)),
                ("reminder_datetime", models.DateTimeField()),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReminderStatus",
            fields=[
                (
                    "reminder_status_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("status_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReminderType",
            fields=[
                (
                    "reminder_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskPriority",
            fields=[
                ("priority_id", models.AutoField(primary_key=True, serialize=False)),
                ("priority_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("status_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
