# Generated by Django 5.2.7 on 2026-08-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0002_task_customer_task_lead"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"permissions": [("assign_task", "Can assign task")]},
        ),
    ]
