# Generated by Django 5.2.7 on 2026-08-26 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0002_initial"),
        ("customer_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.UniqueConstraint(
                fields=("task_id", "meeting_date", "start_time"),
                name="uq_meeting_task_date_time",
            ),
        ),
    ]
