# Generated by Django 5.2.7 on 2026-08-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0003_alter_task_options"),
        ("Task", "0006_alter_meeting_meeting_status_id_and_more"),
    ]

    operations = []
