# Generated by Django 5.2.7 on 2026-08-20 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0011_alter_task_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meetingparticipant",
            constraint=models.UniqueConstraint(
                fields=("meeting_id", "user_id"), name="uq_meeting_participant"
            ),
        ),
    ]
