# Generated by Django 5.2.7 on 2026-08-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FollowUp", "0002_delete_followupnote"),
        ("FollowUp", "0005_remove_notificationtemplate_notification_type_id_and_more"),
    ]

    operations = []
