# Generated by Django 5.2.7 on 2026-08-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FollowUp", "0007_add_is_active_soft_delete_fields"),
        ("FollowUp", "0007_remove_activitylog_activity_action_id_and_more"),
    ]

    operations = []
