# Generated by Django 5.2.7 on 2026-08-17 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_management", "0004_lead_lead_assigned_status_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotation",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("submit_quotation", "Can submit quotation for approval"),
                    ("approve_quotation", "Can approve quotation"),
                    ("send_quotation", "Can send quotation"),
                    ("accept_quotation", "Can accept quotation"),
                    ("reject_quotation", "Can reject quotation"),
                    ("request_quotation_revision", "Can request quotation revision"),
                    ("generate_quotation_pdf", "Can generate quotation PDF"),
                ],
            },
        ),
        migrations.AddField(
            model_name="quotation",
            name="accepted_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="customer_management.quotationversion",
            ),
        ),
        migrations.AddField(
            model_name="quotationversion",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotationversion",
            name="revision_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quotationversion",
            name="sent_to",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("CALL", "Call"),
                    ("EMAIL", "Email"),
                    ("MEETING", "Meeting"),
                    ("DEMO", "Demo"),
                    ("FOLLOW_UP", "Follow Up"),
                    ("QUOTATION_CREATED", "Quotation Created"),
                    ("QUOTATION_UPDATED", "Quotation Updated"),
                    ("QUOTATION_SUBMITTED", "Quotation Submitted"),
                    ("QUOTATION_APPROVED", "Quotation Approved"),
                    ("QUOTATION_APPROVAL_REJECTED", "Quotation Approval Rejected"),
                    ("QUOTATION_SENT", "Quotation Sent"),
                    ("QUOTATION_REVISION_REQUESTED", "Quotation Revision Requested"),
                    ("QUOTATION_VERSION_CREATED", "Quotation Version Created"),
                    ("QUOTATION_ACCEPTED", "Quotation Accepted"),
                    ("QUOTATION_REJECTED", "Quotation Rejected"),
                    ("QUOTATION_PDF_GENERATED", "Quotation PDF Generated"),
                    ("QUOTATION_EMAIL_SENT", "Quotation Email Sent"),
                ],
                max_length=30,
            ),
        ),
    ]
