"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / ".env")

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = (
    os.getenv("ALLOWED_HOSTS").split(",") if os.getenv("ALLOWED_HOSTS") else []
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "accounts",
    "audit_log",
    "Task",
    "FollowUp",
    "customer_management",
    "Notification",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "crm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "crm.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# settings.py

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "1000/day",
        "anon": "100/day",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# ======================================================
# DRF-SCPECTACULAR (OpenAPI / Swagger)
# ======================================================

SPECTACULAR_SETTINGS = {
    "TITLE": "DemoCRM API",
    "DESCRIPTION": (
        "REST API for the DemoCRM customer relationship management system.\n\n"
        "## Authentication\n"
        "This API uses **JWT (JSON Web Tokens)** for authentication. "
        "Obtain an access token via the `/api/login/` endpoint and include it "
        "in the `Authorization` header as `Bearer <access_token>`.\n\n"
        "## API Modules\n"
        "- **Accounts** - User registration, login, logout, profiles, roles, and permissions.\n"
        "- **Customer Management** - Leads, customers, pipelines, quotation workflows, activities, and audit logs.\n"
        "- **Tasks** - Task management with assignments and status tracking.\n"
        "- **Meetings** - Meeting scheduling, rescheduling, participants.\n"
        "- **Reminders** - Reminder creation and management.\n"
        "- **Follow-ups** - Follow-up tracking with notes.\n"
        "- **Notifications** - User notifications.\n\n"
        "## Pagination\n"
        "List endpoints that support pagination return results in a paginated format "
        "with `page` and `page_size` query parameters.\n\n"
        "## Permissions\n"
        "Most endpoints require authentication. Some endpoints have role-based access "
        "control (Admin, Manager, Employee)."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "TAGS": [
        {
            "name": "Accounts",
            "description": "Authentication, user profiles, roles, and permissions",
        },
        {"name": "Leads", "description": "Lead management and workflow operations"},
        {"name": "Customers", "description": "Customer management"},
        {"name": "Pipelines", "description": "Pipeline and pipeline stage management"},
        {
            "name": "Quotations",
            "description": "Quotation creation, workflow, approvals, and PDF generation",
        },
        {"name": "Tasks", "description": "Task management"},
        {
            "name": "Meetings",
            "description": "Meeting scheduling and participant management",
        },
        {"name": "Reminders", "description": "Reminder management"},
        {"name": "Follow Ups", "description": "Follow-up tracking and notes"},
        {"name": "Notifications", "description": "User notifications"},
        {"name": "Audit Logs", "description": "System audit logs"},
        {"name": "Lead Sources", "description": "Lead source management"},
        {"name": "Activities", "description": "Activity tracking"},
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "USER_ID_FIELD": "user_id",
    "USER_ID_CLAIM": "user_id",
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
}

AUTH_USER_MODEL = "accounts.CustomUser"

# ======================================================
# EMAIL CONFIGURATION
# ======================================================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com").strip("'\" ")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").strip("'\" ").lower() == "true"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip("'\" ")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip("'\" ")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER).strip("'\" ")

# ======================================================
# LOGGER
# ======================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} [{name}:{lineno}] {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": True,
        },
        "customer_management": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "accounts": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "Task": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "FollowUp": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "Notification": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
# ==============================================================================
# CELERY & REDIS SETTINGS
# ==============================================================================
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata" 

from celery.schedules import crontab

# CELERY BEAT PERIODIC SCHEDULES
CELERY_BEAT_SCHEDULE = {

    "send-task-due-reminders-daily": {
        "task": "Task.tasks.task_due_reminder_job",
        "schedule": crontab(hour=9, minute=0), 
    },
    "process-meeting-reminders-every-5-mins": {
        "task": "Task.tasks.meeting_reminder_job",
        "schedule": crontab(minute="*/5"),
    },
}