# Generated by Django 5.2.7 on 2026-08-26 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("CALL", "Call"),
                            ("EMAIL", "Email"),
                            ("MEETING", "Meeting"),
                            ("DEMO", "Demo"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("QUOTATION_CREATED", "Quotation Created"),
                            ("QUOTATION_UPDATED", "Quotation Updated"),
                            ("QUOTATION_SUBMITTED", "Quotation Submitted"),
                            ("QUOTATION_APPROVED", "Quotation Approved"),
                            (
                                "QUOTATION_APPROVAL_REJECTED",
                                "Quotation Approval Rejected",
                            ),
                            ("QUOTATION_SENT", "Quotation Sent"),
                            (
                                "QUOTATION_REVISION_REQUESTED",
                                "Quotation Revision Requested",
                            ),
                            ("QUOTATION_VERSION_CREATED", "Quotation Version Created"),
                            ("QUOTATION_ACCEPTED", "Quotation Accepted"),
                            ("QUOTATION_REJECTED", "Quotation Rejected"),
                            ("QUOTATION_PDF_GENERATED", "Quotation PDF Generated"),
                            ("QUOTATION_EMAIL_SENT", "Quotation Email Sent"),
                            ("TASK_CREATED", "Task Created"),
                            ("TASK_UPDATED", "Task Updated"),
                            ("TASK_DELETED", "Task Deleted"),
                            ("TASK_ASSIGNED", "Task Assigned"),
                            ("TASK_REASSIGNED", "Task Reassigned"),
                            ("TASK_STATUS_CHANGED", "Task Status Changed"),
                            ("FOLLOWUP_CREATED", "Follow-up Created"),
                            ("FOLLOWUP_UPDATED", "Follow-up Updated"),
                            ("FOLLOWUP_DELETED", "Follow-up Deleted"),
                            ("REMINDER_CREATED", "Reminder Created"),
                            ("REMINDER_UPDATED", "Reminder Updated"),
                            ("REMINDER_DELETED", "Reminder Deleted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("outcome", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "activity",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.UUIDField()),
                ("action", models.CharField(max_length=100)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
