# Generated by Django 5.2.7 on 2026-08-17 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("message", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In App"),
                            ("EMAIL", "Email"),
                            ("BOTH", "Both"),
                        ],
                        default="IN_APP",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_template",
                "ordering": ["event_type", "-is_default", "-created_at"],
                "permissions": [
                    ("manage_notification_template", "Can manage notification template")
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("message", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In App"),
                            ("EMAIL", "Email"),
                            ("BOTH", "Both"),
                        ],
                        default="IN_APP",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="Notification.notificationtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at"],
                "permissions": [
                    ("send_manual_notification", "Can send manual notification")
                ],
            },
        ),
    ]
